[package]
name = "chess-script"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
monerochan = { workspace = true }

[build-dependencies]
monerochan-build = { workspace = true }
