[package]
name = "json-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
monerochan-runtime = { path = "../../../crates/zkvm/entrypoint" }
serde_json = { workspace = true }
lib = { path = "../lib", package = "json-lib" }
