[package]
name = "uint256-arith-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
monerochan-runtime = { path = "../../../../crates/zkvm/entrypoint" }
monerochan-derive = { path = "../../../../crates/derive" }
crypto-bigint = { workspace = true }
