[package]
name = "bn254-fp2-mul-test"
version = "1.1.1"
edition = "2021"
publish = false


[dependencies]
monerochan-runtime = { path = "../../../../crates/zkvm/entrypoint" }
num-bigint = { workspace = true }
rand = "0.8.5"
