[package]
version = "0.1.0"
name = "bls12381-script"
edition = "2021"

[dependencies]
monerochan = { path = "../../../crates/sdk" }


[build-dependencies]
monerochan-build = { workspace = true }
