[package]
name = "io-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
monerochan-runtime = { path = "../../../crates/zkvm/entrypoint" }
serde = { workspace = true, features = ["derive"] }
