[package]
name = "bls12381-fp-test"
version = "1.1.1"
edition = "2021"
publish = false


[dependencies]
monerochan-runtime = { path = "../../../../crates/zkvm/entrypoint" }
num-bigint = "0.4.6"
rand = "0.8.5"
